apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  annotations:
    github.com/project-slug: ${{ values.repoOwner }}/${{ values.name }}
    backstage.io/techdocs-ref: dir:.
    tcs.io/team: ${{ values.team }}
    tcs.io/tier: ${{ values.tier }}
    tcs.io/language: python
    tcs.io/maturity: beta
spec:
  type: service
  lifecycle: production
  owner: group:${{ values.team }}
